spring.application.name=Restaurant_POS_System


# Data Source Configs
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver



jwt.secret=${JWT_KEY}

logging.level.org.springframework.security=trace


# JPA Configuration

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Don't include the stacktrace in the error returned in the response
server.error.include-stacktrace=never

#File Uploader
file.upload-dir=uploads/menu
spring.web.resources.static-locations=file:uploads/


#seeding config
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
